# Generated by Django 6.0.1 on 2026-01-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Problems",
            new_name="Problem",
        ),
    ]
