# Generated by Django 6.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_rename_problems_problem"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(help_text="JSON formatida argumentlar, masalan: [1, 2]"),
                ),
                (
                    "expected_output",
                    models.TextField(help_text="Kutilgan natija (string)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Tartib raqami"
                    ),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="Ha bo'lsa, masala sahifasida namuna sifatida ko'rsatiladi",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test case",
                "verbose_name_plural": "Test cases",
                "ordering": ["order", "pk"],
            },
        ),
    ]
