# Generated by Django 6.0.1 on 2026-01-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_rename_problems_problem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="problem",
            options={"verbose_name": "Problem", "verbose_name_plural": "Problems"},
        ),
    ]
