# Generated by Django 6.0.1 on 2026-01-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_merge_20260130_0604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="input_data",
            field=models.TextField(help_text="Vergul bilan ajratilgan: 10, 20"),
        ),
    ]
